### Free Thermal Expansion Verification Simulation
### Uniform temperature ramp with minimal constraints (one point pinned)
### Validates thermal expansion mechanics against analytical solution:
###   u_r(r) = α × ΔT × r (radial displacement)
###   σ_ij = 0 (stress-free)

!include copper_cylinder_base.i

# [Mesh]
  # Add single pin point at origin for rigid body constraint
  # [pin_origin]
  #   type = ExtraNodesetGenerator
  #   input = stabilizer
  #   new_boundary = pin_origin
  #   coord = '0 0 0'
  #   use_closest_node = true
  # []
# []

[Functions]
  # Analytical thermal strain as function of time
  # Generated by generate_analytical_thermal_strain.py using NIST correlation
  # This is INDEPENDENT of MOOSE eigenstrain material (validates it)
  [thermal_strain_analytical]
    type = PiecewiseLinear
    data_file = 'thermal_strain_analytical_vs_time.csv'
    format = columns
    xy_in_file_only = false
  []

  # Analytical displacement components for FINITE STRAIN formulation
  # MOOSE uses logarithmic (Hencky) strain: ε_log = ∫α(T)dT
  # Stretch: λ = exp(ε_log)
  # Displacement: u = position × (λ - 1) = position × (exp(ε_thermal) - 1)
  #
  # Reference: Rashid (1993) "Incremental kinematics for finite element applications"
  #            Malvern (1969) "Introduction to the Mechanics of a Continuous Medium"
  [disp_x_analytical]
    type = ParsedFunction
    expression = 'x * (exp(thermal_strain) - 1)'
    symbol_names = 'thermal_strain'
    symbol_values = 'thermal_strain_analytical'
  []
  [disp_y_analytical]
    type = ParsedFunction
    expression = 'y * (exp(thermal_strain) - 1)'
    symbol_names = 'thermal_strain'
    symbol_values = 'thermal_strain_analytical'
  []
  [disp_z_analytical]
    type = ParsedFunction
    expression = 'z * (exp(thermal_strain) - 1)'
    symbol_names = 'thermal_strain'
    symbol_values = 'thermal_strain_analytical'
  []
[]

[BCs]
  # Minimal constraint: fix origin to prevent rigid body translation
  # [pin_origin_x]
  #   type = ADDirichletBC
  #   variable = disp_x
  #   boundary = 'pin_origin'
  #   value = 0
  # []
  # [pin_origin_y]
  #   type = ADDirichletBC
  #   variable = disp_y
  #   boundary = 'pin_origin'
  #   value = 0
  # []
  # [pin_origin_z]
  #   type = ADDirichletBC
  #   variable = disp_z
  #   boundary = 'pin_origin'
  #   value = 0
  # []
  [pin_x]
    type = ADFunctionDirichletBC
    variable = disp_x
    boundary = 'pin_bottom_90_deg'
    function = disp_x_analytical
  []
  [pin_y]
    type = ADFunctionDirichletBC
    variable = disp_y
    boundary = 'pin_bottom_0_deg pin_bottom_180_deg'
    function = disp_y_analytical
  []
  [pin_z]
    type = ADFunctionDirichletBC
    variable = disp_z
    boundary = 'pin_bottom_0_deg pin_bottom_90_deg pin_bottom_180_deg'
    function = disp_z_analytical
  []

  # [fix_boundaries_x]
  #   type = ADFunctionDirichletBC
  #   boundary = 'pin_origin axial_end axial_start outer'
  #   variable = disp_x
  #   function = disp_x_analytical
  # []
  #   [fix_boundaries_y]
  #   type = ADFunctionDirichletBC
  #   boundary = 'pin_origin axial_end axial_start outer'
  #   variable = disp_y
  #   function = disp_y_analytical
  # []
  #   [fix_boundaries_z]
  #   type = ADFunctionDirichletBC
  #   boundary = 'pin_origin axial_end axial_start outer'
  #   variable = disp_z
  #   function = disp_z_analytical
  # []
[]

[Postprocessors]
  # Displacement error norms - CSV only
  # L2: ||u_MOOSE - u_analytical||_L2 = sqrt(∫_Ω |u_MOOSE - u_analytical|² dV)
  # Skip INITIAL to avoid t=0 numerical noise
  [disp_x_L2_error]
    type = ElementL2Error
    variable = disp_x
    function = disp_x_analytical
    execute_on = 'TIMESTEP_END'
  []
  [disp_y_L2_error]
    type = ElementL2Error
    variable = disp_y
    function = disp_y_analytical
    execute_on = 'TIMESTEP_END'
  []
  [disp_z_L2_error]
    type = ElementL2Error
    variable = disp_z
    function = disp_z_analytical
    execute_on = 'TIMESTEP_END'
  []

  # H1 seminorm: gradient error only - CSV only
  # |u|_H1-semi = ||∇u||_L2 = sqrt(∫_Ω |∇u|² dV)
  # Measures strain-like errors (gradient mismatch)
  # Skip INITIAL to avoid t=0 numerical noise
  [disp_x_H1semi_error]
    type = ElementH1SemiError
    variable = disp_x
    function = disp_x_analytical
    execute_on = 'TIMESTEP_END'
    outputs = 'csv'
  []
  [disp_y_H1semi_error]
    type = ElementH1SemiError
    variable = disp_y
    function = disp_y_analytical
    execute_on = 'TIMESTEP_END'
    outputs = 'csv'
  []
  [disp_z_H1semi_error]
    type = ElementH1SemiError
    variable = disp_z
    function = disp_z_analytical
    execute_on = 'TIMESTEP_END'
    outputs = 'csv'
  []

  # Strain error norms - CSV only
  # L2: ||ε_MOOSE - ε_analytical||_L2
  # Captures spatial non-uniformity in strain field
  # For free thermal expansion: ε_xx = ε_yy = ε_zz = thermal_strain_analytical
  # Skip INITIAL to avoid t=0 numerical noise
  [strain_xx_L2_error]
    type = ElementL2Error
    variable = strain_xx
    function = thermal_strain_analytical
    execute_on = 'TIMESTEP_END'
    outputs = 'csv'
  []
  [strain_yy_L2_error]
    type = ElementL2Error
    variable = strain_yy
    function = thermal_strain_analytical
    execute_on = 'TIMESTEP_END'
    outputs = 'csv'
  []
  [strain_zz_L2_error]
    type = ElementL2Error
    variable = strain_zz
    function = thermal_strain_analytical
    execute_on = 'TIMESTEP_END'
    outputs = 'csv'
  []

  # Stress L2 norms - CSV only
  # (analytical stress = 0, so this is ||σ_MOOSE - 0||_L2 = ||σ_MOOSE||_L2)
  # Better measure of stress-free quality than max value
  # Skip INITIAL to avoid artifacts at t=0
  [stress_xx_L2_norm]
    type = ElementL2Norm
    variable = stress_xx
    execute_on = 'TIMESTEP_END'
    outputs = 'csv'
  []
  [stress_yy_L2_norm]
    type = ElementL2Norm
    variable = stress_yy
    execute_on = 'TIMESTEP_END'
    outputs = 'csv'
  []
  [stress_zz_L2_norm]
    type = ElementL2Norm
    variable = stress_zz
    execute_on = 'TIMESTEP_END'
    outputs = 'csv'
  []
  [stress_xy_L2_norm]
    type = ElementL2Norm
    variable = stress_xy
    execute_on = 'TIMESTEP_END'
    outputs = 'csv'
  []
  [stress_xz_L2_norm]
    type = ElementL2Norm
    variable = stress_xz
    execute_on = 'TIMESTEP_END'
    outputs = 'csv'
  []
  [stress_yz_L2_norm]
    type = ElementL2Norm
    variable = stress_yz
    execute_on = 'TIMESTEP_END'
    outputs = 'csv'
  []
[]

[AuxVariables]
  # Element-wise displacement errors for visualization in Paraview
  [disp_x_error]
    order = CONSTANT
    family = MONOMIAL
  []
  [disp_y_error]
    order = CONSTANT
    family = MONOMIAL
  []
  [disp_z_error]
    order = CONSTANT
    family = MONOMIAL
  []
[]

[AuxKernels]
  # Compute element-wise errors: |u_MOOSE - u_analytical|
  [disp_x_error_aux]
    type = ElementL2ErrorFunctionAux
    variable = disp_x_error
    coupled_variable = disp_x
    function = disp_x_analytical
  []
  [disp_y_error_aux]
    type = ElementL2ErrorFunctionAux
    variable = disp_y_error
    coupled_variable = disp_y
    function = disp_y_analytical
  []
  [disp_z_error_aux]
    type = ElementL2ErrorFunctionAux
    variable = disp_z_error
    coupled_variable = disp_z
    function = disp_z_analytical
  []
[]

[VectorPostprocessors]
  # Sample displacement along radial rays at mid-height for verification
  # Compare MOOSE solution to analytical u(r) = r × ε_thermal
  [disp_ray_0deg]
    type = LineValueSampler
    start_point = '0 0 225'  # Center at mid-height (z = 450/2 = 225 mm)
    end_point = '10 0 225'   # Outer radius along x-axis (0°)
    num_points = 50
    variable = 'disp_x disp_y disp_z'
    sort_by = x
    outputs = 'csv'
  []
  [disp_ray_45deg]
    type = LineValueSampler
    start_point = '0 0 225'
    end_point = '7.071 7.071 225'  # r=10mm at 45° (10/√2, 10/√2)
    num_points = 50
    variable = 'disp_x disp_y disp_z'
    sort_by = id
    outputs = 'csv'
  []
  [disp_ray_90deg]
    type = LineValueSampler
    start_point = '0 0 225'
    end_point = '0 10 225'  # Outer radius along y-axis (90°)
    num_points = 50
    variable = 'disp_x disp_y disp_z'
    sort_by = y
    outputs = 'csv'
  []

  # Sample along z-axis to check axial displacement
  [disp_axial]
    type = LineValueSampler
    start_point = '0 0 0'     # Bottom
    end_point = '0 0 450'     # Top
    num_points = 50
    variable = 'disp_x disp_y disp_z'
    sort_by = z
    outputs = 'csv'
  []
[]

[Outputs]
  [exodus]
    type = Exodus
    file_base = 'data/copper_cylinder_free_thermal_expansion_out'
  []
  [csv]
    type = CSV
    file_base = 'data/copper_cylinder_free_thermal_expansion_out'
  []
[]
